# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET + Angular

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4

    ########################################
    # .NET
    ########################################

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore NuGet Packages
      run: dotnet restore backend/Twitter-backend/Twitter-backend.csproj

    - name: Build .NET
      run: dotnet build backend/Twitter-backend/Twitter-backend.csproj --configuration Release --no-restore

    - name: Run .NET Tests
      run: dotnet test backend/Twitter-backend/Twitter-backend.csproj --no-build

    ########################################
    # Angular
    ########################################

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Angular Packages
      working-directory: Frontend
      run: npm install

    - name: Build Angular
      working-directory: Frontend
      run: npm run build
