import { Component, EventEmitter, Input, Output, ElementRef, HostListener } from '@angular/core';

interface EmojiCategory {
  name: string;
  icon: string;
  emojis: string[];
}

const EMOJI_NAMES: { [emoji: string]: string } = {
  // Smileys & People
  '😀': 'grinning face happy smile grin laugh joy',
  '😃': 'grinning face with big eyes happy smile mouth open laugh joy',
  '😄': 'grinning face with smiling eyes happy smile laugh joy',
  '😁': 'beaming face with smiling eyes happy smile grin laugh joy teeth',
  '😆': 'grinning squinting face happy laugh squint grin joy',
  '😅': 'grinning face with sweat happy laugh sweat exercise',
  '🤣': 'rolling on the floor laughing rofl laugh joy humor funny',
  '😂': 'face with tears of joy laugh tears crying joy humor funny',
  '🙂': 'slightly smiling face smile happy',
  '🙃': 'upside down face silly crazy sarcasm',
  '😉': 'winking face wink blink sly',
  '😊': 'smiling face with smiling eyes blush happy smile shy',
  '😇': 'smiling face with halo angel innocent good heaven',
  '🥰': 'smiling face with hearts love romance adore hearts blushing',
  '😍': 'smiling face with heart eyes love adore heart eye romantic',
  '🤩': 'star struck excited star eyes wow amazing',
  '😘': 'face blowing a kiss love kiss blow lips romance',
  '😗': 'kissing face kiss lips',
  '😚': 'kissing face with closed eyes kiss lips blush romance',
  '😙': 'kissing face with smiling eyes kiss lips smile',
  '🥲': 'smiling face with tear happy sad cry mixed relief',
  '😋': 'face savoring food delicious yum tasty hungry tongue',
  '😛': 'face with tongue playful fun silly tease',
  '😜': 'winking face with tongue wink play tease crazy silly',
  '🤪': 'zany face crazy wild goofy silly eye',
  '😝': 'squinting face with tongue play tease squint goofy',
  '🤑': 'money mouth face rich money dollars cash greed',
  '🤗': 'hugging face hug embrace welcome warmth open hands',
  '🤭': 'face with hand over mouth oops giggle gasp secret',
  '🫢': 'face with open eyes and hand over mouth shock gasp oops',
  '🫣': 'face with peeping eye peek hide fear shy watch',
  '🤫': 'shushing face quiet shh silence whisper secret',
  '🤔': 'thinking face think wonder guess ponder query',
  '🫡': 'saluting face salute respect military honor yes',
  '🤐': 'zipper mouth face zip silent secret lock quiet',
  '🤨': 'face with raised eyebrow suspicious skeptik huh raise',
  '😐': 'neutral face poker face meh flat',
  '😑': 'expressionless face meh sigh flat bored',
  '😶': 'face without mouth quiet silent speech less blank',
  '🫥': 'dotted line face invisible hide disappear fade',
  '😏': 'smirking face smirk sly smug sarcasm',
  '😒': 'unamused face meh bored unhappy disapprove grumpy',
  '🙄': 'face with rolling eyes eye roll bore dismiss whatever',
  '😬': 'grimacing face grimace oops nervous tight teeth',
  '🤥': 'lying face lie pinocchio nose long tell truth false',
  '😌': 'relieved face relief calm peace rest satisfy sigh',
  '😔': 'pensive face sad sorrow regret worry lonely',
  '😪': 'sleepy face tired sleep bubble rest',
  '🤤': 'drooling face drool sleep saliva delicious yummy',
  '😴': 'sleeping face sleep zzz tired rest bed',
  '😷': 'face with medical mask sick doctor health virus protect mask',
  '🤒': 'face with thermometer sick ill fever temperature cold',
  '🤕': 'face with head bandage hurt head injury pain accident',
  '🤢': 'nauseated face sick throw up disgust green vomit',
  '🤮': 'face vomiting sick puke barf spew throw up',
  '🥵': 'hot face heat sweat sunburn warm summer red',
  '🥶': 'cold face freeze ice winter blue cold',
  '🥴': 'woozy face dizzy drunk sick tired lightheaded',
  '😵': 'dizzy face cross eyes dead shock surprise',
  '🤯': 'exploding head mind blown shock surprise wow amazing',
  '🤠': 'cowboy hat face wild west country cowboy',
  '🥳': 'partying face party celebrate birthday horn hat blower',
  '🥸': 'disguised face glasses mustache mask disguise spy hide',
  '😎': 'smiling face with sunglasses cool shades sunglasses style fashion summer',
  '🤓': 'nerd face geek smart study books glasses',
  '🧐': 'face with monocle class smart curious rich search inspect',
  '😕': 'confused face confuse huh query worry puzzled',
  '🫤': 'face with diagonal mouth unsure meh skeleton sigh skew',
  '😟': 'worried face worry sad anxiety stress concern',
  '🙁': 'slightly frowning face sad unhappy frown',
  '😮': 'face with open mouth gasp wow surprise shock open',
  '😯': 'hushed face surprise quiet whisper soft gasp',
  '😲': 'astonished face shock surprise wow gasp amaze',
  '😳': 'flushed face blush red cheek shock embarrassed surprise',
  '🥺': 'pleading face please beg puppy eyes cry sad mercy',
  '🥹': 'face holding back tears emotional proud touch happy tears',
  '😦': 'frowning face with open mouth sad shock surprise gasp',
  '😧': 'anguished face sad worry pain fear shock',
  '😨': 'fearful face fear scare shock scream terror',
  '😰': 'anxious face with sweat worry stress sweat blue face',
  '😥': 'sad but relieved face worry relief sweat cry drop',
  '😢': 'crying face sad tear cry weep sorrow',
  '😭': 'loudly crying face sad tear cry sob scream sorrow wail',
  '😱': 'face screaming in fear scream scare fear shock munch terror',
  '😖': 'confounded face upset pain struggle twitch',
  '😣': 'persevering face persist struggle tight eye stubborn',
  '😞': 'disappointed face sad depress regret sorrow',
  '😓': 'downcast face with sweat sad worry sweat stress exhaust',
  '😩': 'weary face tired sigh exhaust moan complain',
  '😫': 'tired face yawn exhaust sleep complain sigh',
  '🥱': 'yawning face yawn tired sleep bore',
  '😤': 'face with steam from nose angry mad rage win proud victory',
  '😡': 'pouting face angry mad rage red pout fume',
  '😠': 'angry face mad rage frown annoy vexed',
  '🤬': 'face with symbols on mouth curse swear swearword anger mad censor',
  '😈': 'smiling face with horns devil evil demon bad purple',
  '👿': 'angry face with horns devil evil demon bad purple mad',
  '💀': 'skull bone dead ghost skeleton halloween',
  '☠️': 'skull and crossbones poison danger death pirate halloween',
  '💩': 'pile of poo poop turd toilet compost',
  '🤡': 'clown face circus funny makeup joke',
  '👹': 'ogre red monster devil mask ogre japanese folklore',
  '👺': 'goblin red monster nose long mask japanese folklore',
  '👻': 'ghost spook phantom white halloween scary',
  '👽': 'alien space ufo extraterrestrial martian outer',
  '👾': 'alien monster retro video game space pixel',
  '🤖': 'robot face bot android electronic machine',

  // Gestures & Hands
  '👋': 'waving hand wave hello hi goodbye greet',
  '🤚': 'raised back of hand slap stop high five',
  '🖐️': 'hand with fingers splayed palm open five spread',
  '✋': 'raised hand stop high five palm five',
  '🖖': 'vulcan salute live long prosper spock startrek',
  '🫱': 'rightwards hand reach offer grab shaking',
  '🫲': 'leftwards hand reach offer grab shaking',
  '🫳': 'palm down hand drop let go release',
  '🫴': 'palm up hand catch receive hold lift support',
  '🫷': 'leftwards pushing hand push stop block press',
  '🫸': 'rightwards pushing hand push stop block press',
  '👌': 'ok hand okay correct good perfect fine alright sign',
  '🤌': 'pinched fingers what do you want italian gesture ask query',
  '🤏': 'pinching hand small little tiny bit gap',
  '✌️': 'victory hand peace sign two fingers win double',
  '🤞': 'crossed fingers luck hope promise cross',
  '🫰': 'hand with index finger and thumb crossed heart sign fingerheart love K-pop',
  '🤟': 'love you gesture hand rock love fingers',
  '🤘': 'sign of the horns rock roll metal devil sign hand music',
  '🤙': 'call me hand phone dial contact status reach',
  '👈': 'backhand index pointing left point left direction',
  '👉': 'backhand index pointing right point right direction',
  '👆': 'backhand index pointing up point up direction ceiling',
  '🖕': 'middle finger flip off rude offensive insult hand',
  '👇': 'backhand index pointing down point down direction floor',
  '☝️': 'index pointing up point up finger number one first sky',
  '🫵': 'index pointing at the viewer you direct point self reference',
  '👍': 'thumbs up good like yes agree ok approve positive thumbsup',
  '👎': 'thumbs down bad dislike no disagree reject negative thumbsdown',
  '✊': 'raised fist power strength rebel protest solid punch',
  '👊': 'oncoming fist punch power fight hit strike hello bump fistbump',
  '🤛': 'left-facing fist punch hit bump greeting left',
  '🤜': 'right-facing fist punch hit bump greeting right',
  '👏': 'clapping hands clap applaud praise bravo congrats',
  '🙌': 'raising hands celebrate party praise hooray high ten',
  '🫶': 'heart hands love heart shape romance adore care support',
  '👐': 'open hands hug reach stretch offer spread',
  '🤲': 'palms up together pray book ask hands open',
  '🤝': 'handshake shake hands agreement business deal trust welcome',
  '🙏': 'folded hands pray please thank you namaste hope gratitude bless',
  '💪': 'flexed biceps muscle strength power exercise gym flex strong fitness',
  '🦾': 'mechanical arm robot arm prosthesis metal strength bionic',
  '🦿': 'mechanical leg robot leg prosthesis metal bionic',
  '🦵': 'leg foot limb walk run kick',
  '🦶': 'foot walk run stamp sole kick stand step',
  '👂': 'ear listen hear sound noise acoustic',
  '🦻': 'ear with hearing aid hear deaf assist sign',
  '👃': 'nose smell sniff breath odor perfume',
  '🧠': 'brain mind head think smart intellect genius anatomy',
  '🫀': 'anatomical heart heart organ pulse blood medicine medical cardio',
  '🫁': 'lungs organ breathe chest breath medicine medical respiration',
  '🦷': 'tooth teeth dentist dental clean bite chew',
  '🦴': 'bone skeleton dog bone anatomy structure',
  '👀': 'eyes look see watch stare peek view curious eye',
  '👁️': 'eye look see watch stare vision',
  '👅': 'tongue mouth lick taste tease',
  '👄': 'mouth lips speak kiss talk whisper red',
  '🫦': 'biting lips bite lip kiss sexy romance passion',

  // Hearts & Love
  '❤️': 'red heart love romance passion heart red adore',
  '🧡': 'orange heart love orange warm support',
  '💛': 'yellow heart love yellow friendship support',
  '💚': 'green heart love green nature eco support jealous',
  '💙': 'blue heart love blue trust loyalty support calm',
  '💜': 'purple heart love purple wealth loyalty respect support',
  '🖤': 'black heart love black sad sorrow dark gothic emo mourning',
  '🤍': 'white heart love white pure peace support clean',
  '🤎': 'brown heart love brown cocoa chocolate support warm earthy',
  '💔': 'broken heart love sad heartbreak separation split divorce pain sorrow',
  '❤️‍🔥': 'heart on fire love burning hot passion flame sexy desire',
  '❤️‍🩹': 'mending heart love recovery heal bandaid hope rest',
  '❣️': 'heart exclamation love warning notice exclamation point mark red',
  '💕': 'two hearts love hearts double pink romantic friendship',
  '💞': 'revolving hearts love hearts circle spin romance',
  '💓': 'beating heart love heart pulse vibration heat rapid pink',
  '💗': 'growing heart love heart size scale pink romance expand',
  '💖': 'sparkling heart love heart sparkle shine glitter glow romantic pink',
  '💘': 'heart with arrow love arrow cupid valentine romance strike shoot',
  '💝': 'heart with ribbon love ribbon gift present valentine chocolate package box',
  '💟': 'heart decoration love heart square frame ornament art decoration',
  '♥️': 'heart suit love card game suit heart red poker board',
  '💌': 'love letter love mail letter stamp envelope post romance note',
  '💋': 'kiss mark love kiss red lips makeup lipstick print',
  '💏': 'kiss love kiss couple romance together red heart',
  '💑': 'couple with heart love couple romance together red heart marriage',
  '👩‍❤️‍👨': 'couple with heart woman man love romance together marriage red heart family',

  // Animals & Nature
  '🐶': 'dog face dog pet puppy animal bark canine',
  '🐱': 'cat face cat pet kitten animal meow feline',
  '🐭': 'mouse face mouse pet rodent animal squeak',
  '🐹': 'hamster face hamster pet rodent animal cage wheel',
  '🐰': 'rabbit face rabbit bunny pet animal carrot jump',
  '🦊': 'fox face fox animal wild red intelligent',
  '🐻': 'bear face bear animal wild forest brown grizzly',
  '🐼': 'panda face panda animal bear wild black white bamboo',
  '🐻‍❄️': 'polar bear bear animal wild white arctic ice snow',
  '🐨': 'koala face koala animal bear wild marsupial australia eucalyptus',
  '🐯': 'tiger face tiger animal cat wild striped yellow fierce roar',
  '🦁': 'lion face lion animal cat wild king fierce mane roar',
  '🐮': 'cow face cow animal farm milk beef moo steer bull',
  '🐷': 'pig face pig animal farm pork oink bacon snout',
  '🐸': 'frog face frog animal amphibian green ribbit jump pond',
  '🐵': 'monkey face monkey animal ape chimp banana climb jungle',
  '🙈': 'see no evil monkey monkey cover eyes hide blind',
  '🙉': 'hear no evil monkey monkey cover ears quiet deaf',
  '🙊': 'speak no evil monkey monkey cover mouth silent secret quiet',
  '🐒': 'monkey animal ape chimp banana climb jungle',
  '🐔': 'chicken bird farm hen egg cluck rooster feathers',
  '🐧': 'penguin bird animal wild sea ice fish flightless antarctica cold',
  '🐦': 'bird animal wings fly chirp feathers wild sky',
  '🐤': 'baby chick baby bird chicken yellow chirp young egg',
  '🐣': 'hatching chick baby bird chicken yellow egg hatch open birth',
  '🐥': 'front facing baby chick baby bird chicken yellow young chirp',
  '🪿': 'goose bird farm wild honk migration feathers pond water',
  '🦆': 'duck bird farm wild quack feathers pond water migration',
  '🐦‍⬛': 'blackbird crow raven bird black feathers dark intelligence flight',
  '🦅': 'eagle bird wild wings fly predator hunt prey majesty america',
  '🦉': 'owl bird wild night wise hoot predator hunt wings eyes',
  '📍': 'pin red map mark place location target marker pushpin',
  '🦇': 'bat animal wild night fly cave vampire halloween wings',
  '🐺': 'wolf face wolf animal wild forest dog pack howl',
  '🐗': 'boar animal pig wild forest tusk snout pork',
  '🐴': 'horse face horse animal farm ride stable jockey neigh run speed',
  '🦄': 'unicorn unicorn horse magic fantasy tail horn rainbow dream',
  '🫎': 'moose animal elk deer wild forest antlers wilderness horns',
  '🐝': 'honeybee bee insect honey buzz sting stripe yellow wing',
  '🪲': 'beetle bug insect shell crawl nature beetle',
  '🐛': 'bug caterpillar insect crawl pupa butterfly green worm leaf',
  '🦋': 'butterfly insect wings fly colors beauty transformation nature cocoon',
  '🐌': 'snail bug shell crawl slow slime garden',
  '🐞': 'lady beetle ladybug insect red black spots lucky bug beetle garden',
  '🐜': 'ant insect bug crawl colony group tiny black red',
  '🪰': 'fly housefly insect bug wings buzz dirty pest',
  '🪱': 'worm bug crawl earthworm soil fishing bait',
  '🐢': 'turtle reptile animal shell slow swim pond sea green',
  '🐍': 'snake reptile serpent animal hiss venom crawl rattle',
  '🦎': 'lizard reptile gecko animal tail green crawl climb',
  '🦖': 't rex tyrannosaurus dinosaur extinct reptile predator giant jurassic monster',
  '🦕': 'sauropod brontosaurus dinosaur extinct plant-eater giant jurassic long neck',
  '🐙': 'octopus sea ocean animal tentacles ink water mollusk',
  '🦑': 'squid sea ocean animal tentacles water ink mollusk',
  '🪼': 'jellyfish sea ocean animal water sting glow translucent',
  '🦐': 'shrimp sea ocean animal water shell pink food seafood',
  '🦞': 'lobster sea ocean animal water claws shell red food seafood claws',
  '🦀': 'crab sea ocean animal water claws shell red food seafood side walk beach',
  '🐡': 'blowfish sea ocean animal water puff spike balloon round',
  '🐠': 'tropical fish sea ocean animal water colorful reef fish aquarium',
  '🐟': 'fish sea ocean animal water scale swim gill food seafood aquarium',
  '🐬': 'dolphin sea ocean animal water dolphin dolphin jump blue smart play',
  '🐳': 'spouting whale sea ocean animal water whale spout water jump giant blue',
  '🐋': 'whale sea ocean animal water whale giant blue mammal',
  '🦈': 'shark sea ocean animal water predator hunt teeth dorsal fin blue gray',
  '🪸': 'coral sea ocean reef rock water environment fish underwater',
  '🐊': 'crocodile alligator reptile predator swamp teeth water green scale',
  '🐅': 'tiger animal cat wild striped yellow fierce roar body stripe',
  '🐆': 'leopard animal cat wild spotted spots speed run fierce panther',
  '🦓': 'zebra animal horse wild stripe black white stripe africa safari',
  '🫏': 'donkey animal farm mule bray pack beast burden ears gray',
  '🦍': 'gorilla animal ape wild jungle silverback monkey giant strong',
  '🦧': 'orangutan animal ape wild jungle monkey orange red arms swing tree',
  '🦣': 'mammoth extinct elephant ice age fur tusks giant trunk wild',
  '🐘': 'elephant animal wild trunk tusks ears giant gray safari india africa',
  '🦛': 'hippopotamus hippo animal wild water giant jaws fat gray swamp safari',
  '🦏': 'rhinoceros rhino animal wild horn giant grey shield safari armour',
  '🐪': 'camel dromedary animal desert hump sand ride camel',
  '🐫': 'two hump camel bactrian animal desert humps sand ride camel',
  '🦒': 'giraffe animal neck long spots tall yellow africa safari tree leaf',
  '🦘': 'kangaroo animal marsupial jump bounce bag baby pouch australia',

  // Food & Drink
  '🍏': 'green apple apple fruit green sweet tart fresh food',
  '🍎': 'red apple apple fruit red sweet fresh food crisp',
  '🍐': 'pear fruit sweet green yellow fresh food',
  '🍊': 'tangerine orange fruit citrus sweet peel juice fresh food',
  '🍋': 'lemon fruit citrus sour yellow juice scale fresh food squeeze',
  '🍌': 'banana fruit yellow sweet peel potassium monkey fresh food',
  '🍉': 'watermelon fruit green red seeds slice sweet summer fresh food water',
  '🍇': 'grapes grape fruit purple green wine bunch sweet fresh food',
  '🍓': 'strawberry fruit red seeds sweet berry fresh food summer red',
  '🫐': 'blueberries blueberry fruit blue sweet berry fresh food healthy',
  '🍈': 'melon cantaloupe fruit sweet green orange fresh food slice',
  '🍒': 'cherries cherry fruit red stem sweet fresh food double',
  '🍑': 'peach fruit pink orange sweet fuzzy fresh food butt shape',
  '🥭': 'mango fruit tropical sweet orange yellow juice fresh food',
  '🍍': 'pineapple fruit tropical yellow spike sweet fresh food crown',
  '🥥': 'coconut fruit tropical brown hard milk white fresh food palm tree',
  '🥝': 'kiwi fruit brown green fuzzy slice sour sweet fresh food',
  '🍅': 'tomato fruit vegetable red seeds salad pizza sauce food fresh',
  '🍆': 'eggplant vegetable purple aubergine cooking food plant dick',
  '🥑': 'avocado fruit green pit toast salad guac healthy fat food guacamole',
  '🫛': 'pea pod peas vegetable green pod healthy cooking food',
  '🥦': 'broccoli vegetable green tree healthy cooking food nutrition',
  '🥬': 'leafy green lettuce cabbage salad green healthy cooking food',
  '🥒': 'cucumber vegetable green pickle salad water cool crisp food',
  '🌶️': 'hot pepper chili pepper vegetable red spicy hot burn heat cooking food',
  '🫑': 'bell pepper vegetable green red yellow sweet pepper cooking food salad',
  '🌽': 'ear of corn corn cob yellow farm sweet popcorn vegetable food grain',
  '🥕': 'carrot vegetable orange rabbit beta carotene healthy sweet food roots',
  '🧄': 'garlic vegetable white bulb smell spice cook flavor seasoning food bulb',
  '🧅': 'onion vegetable purple white layer slice cook cry smell flavor food bulb',
  '🫒': 'olive fruit green black oil martini pizza food greek tapenade',
  '🥔': 'potato vegetable brown starch french fry potato baking food tuber',
  '🍠': 'roasted sweet potato potato purple sweet starch baking food tuber',
  '🫚': 'ginger root vegetable brown spice cook ginger ale flavor food',
  '🥐': 'croissant bread pastry bakery French buttery breakfast flaky food baking',
  '🥯': 'bagel bread bakery breakfast round hole cream cheese toasted food baking',
  '🍞': 'bread loaf bakery slice sandwich wheat food baking toast',
  '🫓': 'flatbread bread pita naan wrap baking flour food flat',
  '🥖': 'baguette bread loaf French bakery long crusty food baking',
  '🥨': 'pretzel bakery salt twist knot snack beer food baking',
  '🧀': 'cheese wedge cheese dairy yellow holes swiss cheese food mouse pizza',
  '🥚': 'egg white shell chicken breakfast yolk protein bird nest food cooking',
  '🍳': 'cooking pan egg fry breakfast pan yellow yolk hot plate food stove',
  '🧈': 'butter dairy block yellow toast fat grease cook baking food slice',
  '🥞': 'pancakes hotcakes breakfast stack syrup butter sweet bakery food baking',
  '🧇': 'waffle breakfast grid syrup butter sweet bakery food baking grid',
  '🥓': 'bacon meat pork strips grease fry breakfast smoke salty food strip',
  '🥩': 'cut of meat steak beef pork raw barbecue grill protein dinner food red',
  '🍗': 'poultry leg chicken drumstick meat turkey barbecue fry food bone',
  '🍖': 'meat on bone cartoon steak pork roast anime meat bone food',
  '🌭': 'hot dog hotdog sausage bun mustard ketchup barbecue snack fastfood food',
  '🍔': 'hamburger burger meat cheese bun lettuce fastfood beef grill food burger',
  '🍟': 'french fries fries potato fastfood salt snack yellow ketchup box food',
  '🍕': 'pizza slice cheese pepperoni tomato crust fastfood italian delivery food slice',
  '🫔': 'tamale corn husk meat dough Mexican traditional steam wrap food',
  '🌮': 'taco shell meat lettuce cheese tomato Mexican fastfood tortilla dinner food',
  '🌯': 'burrito wrap meat rice beans cheese Mexican fastfood tortilla roll food',
  '🫕': 'fondue cheese chocolate dip pot flame sticks bread fruit food pot',
  '🥙': 'stuffed flatbread falafel pita kebab salad wrap gyro middle eastern food',
  '🧆': 'falafel chickpea ball vegetarian middle eastern fry herb spice food balls',
  '🥗': 'green salad lettuce tomato cucumber healthy vegetable vegan olive oil bowl food',
  '🍝': 'spaghetti pasta noodle sauce meatballs tomato fork italian dinner food bowl',
  '🍜': 'steaming bowl ramen noodles soup chopsticks japanese hot broth dinner food',
  '🍲': 'pot of food stew soup hot pot cook dinner meal vegetable meat broth bowl',
  '🍛': 'curry rice plate spicy indian japanese asian sauce dinner food meal',
  '🍣': 'sushi rice raw fish seaweed japanese rolls wasabi sashimi ginger food',
  '🍱': 'bento box lunch compartmentalized japanese meal fish rice vegetable food box',
  '🥟': 'dumpling gyoza potsticker dough wrap meat vegetable steam fry food',
  '🦪': 'oyster shell sea ocean water mollusk pearl seafood raw lemon food',
  '🍤': 'fried shrimp tempura sea ocean shrimp shell deep fry seafood fastfood food',
  '🍙': 'rice ball onigiri seaweed japanese rice triangular snack food wrap',
  '🍚': 'cooked rice white rice bowl grain japanese chopsticks food grain',
  '🍘': 'rice cracker senbei snack round brown seaweed crunch food cracker',
  '🍥': 'fish cake with swirl narutomaki soup ramen pink swirl white food slice',
  '🥠': 'fortune cookie cookie dessert paper prophecy chinese bakery sweet food',
  '🥮': 'mooncake cake dessert traditional chinese autumn mid-autumn sweet bakery food',
  '🍢': 'oden skewer fish cake egg stew japanese traditional street food',
  '🍡': 'dango sweet rice dumpling sweet colorful stick pink white green sweet dessert food',
  '🍧': 'shaved ice ice cream sweet cold syrup cup summer dessert spoon food',
  '🍨': 'ice cream cup dessert sweet scoop cold vanilla chocolate cup spoon food',
  '🍦': 'soft serve ice cream cone swirl vanilla chocolate sweet dessert cold summer food cone',
  '🥧': 'pie dessert sweet fruit apple meat baking bakery plate slice crust food',
  '🧁': 'cupcake cake dessert sweet wrapper frosting sprinkle bakery birthday food',
  '🍰': 'shortcake cake slice dessert strawberry whip cream sweet birthday bakery food',
  '🎂': 'birthday cake cake candles celebrate party dessert sweet birthday bakery food',
  '🍮': 'custard pudding flan caramel dessert sweet yellow cup plate food',
  '🍭': 'lollipop candy suck sweet sugar swirl stick colorful child dessert food',
  '🍬': 'candy wrapped sweet sugar chew wrapper purple colorful child dessert food',
  '🍫': 'chocolate bar bar brown sweet cocoa wrapper square dairy dessert food',
  '🍿': 'popcorn corn kernel salted cinema theater snack yellow stripes box food',
  '🍩': 'donut doughnut sweet glaze sprinkle ring hole bakery dessert breakfast food',
  '🍪': 'cookie chocolate chip cookie round brown sweet bakery dessert snack food',
  '🌰': 'chestnut nut brown autumn roasted shell food tree seed',
  '🥜': 'peanuts peanut nut shell legume salt snack crunch food pod',
  '🍯': 'honey pot honey bee yellow sweet syrup bear pot jar food',

  // Activities & Sports
  '⚽': 'soccer football ball sport game kick stadium team play',
  '🏀': 'basketball ball orange sport game bounce net court team play',
  '🏈': 'american football rugby ball sport game throw kick stadium team play',
  '⚾': 'baseball ball sport game throw bat glove stadium team play',
  '🥎': 'softball ball yellow sport game throw bat glove team play',
  '🎾': 'tennis ball racket sport game net court yellow play green',
  '🏐': 'volleyball ball sport game net beach court team play',
  '🏉': 'rugby football ball oval sport game kick run stadium team play',
  '🥏': 'flying disc frisbee beach park toss spin toy plastic play',
  '🎱': 'pool 8 ball billiards cue table game black circle number eight play',
  '🪀': 'yo-yo yoyo toy spin string plastic up down play',
  '🏓': 'ping pong table tennis racket ball paddle game play net',
  '🏸': 'badminton racket shuttlecock birdie net sport game play',
  '🏒': 'ice hockey stick puck ice arena sport game team play rink skating',
  '🏑': 'field hockey stick ball turf sport game team play grass',
  '🥍': 'lacrosse stick pocket ball mesh helmet sport game team play',
  '🏏': 'cricket bat ball wicket sport game team play pitch stadium',
  '🪃': 'boomerang wood throw fly return australia toy play hunt',
  '🥅': 'goal net soccer hockey lacrosse target score play',
  '⛳': 'flag in hole golf ball club green course hole drive play',
  '🪁': 'kite wind sky fly string paper colorful toy park play',
  '🛝': 'playground slide slide child park play outdoor ladder swing',
  '🏹': 'bow and arrow bow arrow archery target shoot weapon hunt play sport',
  '🎣': 'fishing pole fish hook line rod water lake river sport catch play',
  '🤿': 'diving mask snorkel swim water pool sea ocean dive breath explore',
  '🥊': 'boxing glove glove red punch box gym fight strength sport play',
  '🥋': 'martial arts uniform karate judo taekwondo belt white uniform sport gym play',
  '🎽': 'running shirt sash sport track field running run race athlete marathon',
  '🛹': 'skateboard skate board wheels roll trick park street deck play',
  '🛼': 'roller skate skate wheels boot roll rink park retro sport play',
  '🛷': 'sled sleigh snow winter down hill ride wood toboggan play',
  '⛸️': 'ice skate skate blade boot ice skating rink winter sport play',
  '🥌': 'curling stone stone broom ice sheet target sport game team winter play',
  '🎿': 'skis ski boots poles snow winter mountain slope sport play',
  '⛷️': 'skier skis snow winter mountain slope sport play run athlete',
  '🏂': 'snowboarder board snow winter mountain slope trick sport play run athlete',
  '🪂': 'paraglider parachute sky glide wind fly extreme height air flight',
  '🏋️': 'weight lifter barbell weight lift gym strength train fitness athlete barbell bodybuilder',
  '🤼': 'wrestlers wrestle combat fight gym ring mat sport team play athletes',
  '🤸': 'person cartwheeling cartwheel gymnastics flip gym balance trick stretch athlete',
  '🏆': 'trophy cup gold winner first prize award success achievement champion',
  '🥇': '1st place medal gold medal winner first award success champion',
  '🥈': '2nd place medal silver medal winner second award success runner up',
  '🥉': '3rd place medal bronze medal winner third award success third',
  '🏅': 'sports medal medal ribbon award winner achievement success',
  '🎖️': 'military medal medal star ribbon decoration military honor service bravery',
  '🎗️': 'reminder ribbon ribbon yellow awareness support cause charity cancer reminder',
  '🎪': 'circus tent tent stripes show performance clown animal carnival fair amusement',
  '🤹': 'juggling person juggle balls performance skill coordination show trick clown',
  '🎭': 'performing arts masks drama theater comedy tragedy play show mask actor',
  '🩰': 'ballet shoes pointe shoes ribbon pink dance ballerina theater performance',
  '🎨': 'artist palette paint brush canvas colors art creative design paint draw draw',
  '🎬': 'clapperboard movie film director cinema studio action cut screen hollywood',
  '🎤': 'microphone mic sing music karaoke voice performance audio speaker concert',
  '🎧': 'headphone audio music sound listen song earphone podcast DJ',
  '🎼': 'musical score notes music song sheet classical composer staff treble',
  '🎹': 'musical keyboard piano keys music play synth song classical instrument',
  '🥁': 'drum drumsticks music play beat rhythm percussion instrument band concert',
  '🪘': 'long drum percussion music play beat rhythm djembe conga instrument',
  '🎷': 'saxophone sax horn brass music jazz band play instrument classical wind',
  '🎺': 'trumpet horn brass music jazz band parade fanfare orchestra play instrument wind',
  '🪗': 'accordion squeezebox music play keyboard bellows folk instrument traditional',
  '🎸': 'guitar electric guitar string music rock band play song concert instrument',
  '🪕': 'banjo string music country bluegrass play instrument folk',
  '🎻': 'violin fiddle string music classical orchestra bow play instrument',
  '🪈': 'flute music wind play woodwind orchestra classical instrument',
  '🎲': 'game die dice rolling board game luck random square play',
  '♟️': 'chess pawn chess board game strategy king queen play wood',
  '🎯': 'bullseye dart target game board arrow hit circle play accuracy',
  '🎳': 'bowling pin ball lane strike spare sport game play alley pins',

  // Objects
  '⌚': 'watch time wrist clock device hour minute',
  '📱': 'mobile phone smartphone phone cell screen device call digital contact',
  '📲': 'mobile phone with arrow smartphone phone call message screen device arrow incoming cell',
  '💻': 'laptop computer notebook pc device screen keyboard tech programming work office',
  '⌨️': 'keyboard computer keys input device typing coding pc',
  '🖥️': 'desktop computer monitor screen pc device tech office',
  '🖨️': 'printer paper office computer device ink document print',
  '🖱️': 'computer mouse click cursor pointer device navigation pc',
  '🖲️': 'trackball computer mouse click cursor pointer device navigation',
  '💽': 'computer disk minidisc optical disk device data storage music storage media',
  '💾': 'floppy disk diskette computer data storage save icon retro tech',
  '💿': 'optical disk cd dvd blue disc music data storage video media movie',
  '📀': 'dvd optical disk gold disc movie video data storage media music',
  '📼': 'videocassette vhs tape movie video recorder retro media tape',
  '📷': 'camera photo picture photography lens flash device memory capture',
  '📸': 'camera with flash photo picture photography lens flash light device capture',
  '📹': 'video camera video recorder camcorder movie tape film device capture',
  '🎥': 'movie camera projector film video cinema studio hollywood director',
  '📞': 'telephone receiver phone call handle talk speaker contact status',
  '☎️': 'telephone phone landline office home call dial contact',
  '📟': 'pager beeper communication call alert contact retro tech',
  '📠': 'fax machine printer telephone document paper office copy machine',
  '📺': 'television tv screen broadcast movie show media display screen retro',
  '📻': 'radio broadcast antenna music news audio sound dial speaker station receiver',
  '🎙️': 'studio microphone mic audio record voice podcast broadcast sound',
  '🎚️': 'level slider volume mixing console slider audio control sound',
  '🎛️': 'control knobs mixer console dial selector audio control sound parameter adjustment',
  '🧭': 'compass navigate direction north south east west map travel orientate find way explorer',
  '⏱️': 'stopwatch timer time chronometer elapsed time runner clock athletic count',
  '⏲️': 'timer clock kitchen alarm count down time cooking device',
  '⏰': 'alarm clock clock wake up morning time sleep alert bell',
  '🕰️': 'mantelpiece clock antique clock time shelf retro home decor',
  '💡': 'light bulb bulb idea creative thinking energy glow light electricity',
  '🔦': 'flashlight torch light beam path night search electricity dark battery',
  '🕯️': 'candle wax flame fire light dark ritual prayer romantic wax',
  '🧯': 'fire extinguisher red safety emergency fire security gas pressure extinguisher',
  '🛢️': 'oil drum barrel fuel oil chemical storage container metal tank',
  '💸': 'money with wings bill dollar cash money fly away lose spend wings rich',
  '💵': 'dollar bill bank note cash money green dollar currency paper wealth',
  '💴': 'yen bill bank note cash money yen currency paper wealth japan',
  '💶': 'euro bill bank note cash money euro currency paper wealth europe',
  '💷': 'pound bill bank note cash money pound currency paper wealth uk britain',
  '🪙': 'coin money gold silver cash coin coin currency metal wealth change cents',
  '💰': 'money bag bag gold coins dollar cash wealth rich bank save invest',
  '💳': 'credit card card money bank visa mastercard pay purchase cash charge transaction swipe plastic',
  '🪪': 'identification card id card driver license photo document personal info membership card identity',
  '💎': 'gem stone diamond crystal jewel precious rich blue wealth ring proposal jewelry',
  '⚖️': 'balance scale scales justice law courtroom judge legal weight equality scale balance',
  '🪜': 'ladder step ladder climb height steps construction paint tools renovation',
  '🧰': 'toolbox box red tools hammer wrench screwdriver repair handyman workshop',
  '🪛': 'screwdriver tool repair screw tighten handyman workshop construction hardware',
  '🔧': 'wrench spanner tool repair bolt nut plumbing handyman workshop construction',
  '🔨': 'hammer tool nail repair build construct handyman workshop claw construction mallet',
  '⚒️': 'hammer and pick pickaxe tools mining construct repair hammer pick minerals extraction',
  '🛠️': 'hammer and wrench tools construct repair workshop maintenance service engineering',
  '⛏️': 'pickaxe pick tool mining extraction rocks construct repair tunnel',
  '🪚': 'hand saw saw tool wood cutting carpenter forest timber workshop',
  '🔩': 'nut and bolt bolt screw nut hardware tool repair construct metal fastener thread',
  '⚙️': 'gear wheel cog machine industry rotation tech progress mechanical setting settings setting options setting',
  '🪤': 'mouse trap trap catch rodent bait wooden cheese trap capture',
  '🧲': 'magnet red horseshoe magnet physics metal attraction pull force field iron science tool',
  '🔫': 'water pistol gun toy water squirt green weapon shooter squirt gun pool',
  '💣': 'bomb explode blast explosion weapon war fuse fire sparks black ball danger',
  '🧨': 'firecracker red dynamite bomb explode blast fire sparks chinese new year celebration pyrotechnics',
  '🪓': 'axe chop wood lumberjack tool weapon forest trees steel blade',
  '🔪': 'kitchen knife knife blade cut slice cook chef butcher weapon tool steel',
  '🗡️': 'dagger blade short sword knife weapon steel medieval fight warrior',
  '⚔️': 'crossed swords swords fight weapon steel combat war battle duel knights medieval',
  '🛡️': 'shield protect defense armor security safety guard knight medieval police',
  '🚬': 'cigarette smoke smoking puff tobacco cancer danger fire light ash stick'
};

@Component({
  selector: 'app-emoji-picker',
  standalone: false,
  templateUrl: './emoji-picker.component.html',
  styleUrl: './emoji-picker.component.css',
})
export class EmojiPickerComponent {
  @Input() visible: boolean = false;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() emojiSelect = new EventEmitter<string>();

  searchTerm: string = '';
  activeCategory: number = 0;

  categories: EmojiCategory[] = [
    {
      name: 'Smileys',
      icon: '😀',
      emojis: [
        '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃',
        '😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙',
        '🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🫢',
        '🫣','🤫','🤔','🫡','🤐','🤨','😐','😑','😶','🫥',
        '😏','😒','🙄','😬','🤥','😌','😔','😪','🤤','😴',
        '😷','🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯',
        '🤠','🥳','🥸','😎','🤓','🧐','😕','🫤','😟','🙁',
        '😮','😯','😲','😳','🥺','🥹','😦','😧','😨','😰',
        '😥','😢','😭','😱','😖','😣','😞','😓','😩','😫',
        '🥱','😤','😡','😠','🤬','😈','👿','💀','☠️','💩',
        '🤡','👹','👺','👻','👽','👾','🤖',
      ],
    },
    {
      name: 'Gestures',
      icon: '👋',
      emojis: [
        '👋','🤚','🖐️','✋','🖖','🫱','🫲','🫳','🫴','🫷',
        '🫸','👌','🤌','🤏','✌️','🤞','🫰','🤟','🤘','🤙',
        '👈','👉','👆','🖕','👇','☝️','🫵','👍','👎','✊',
        '👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝','🙏',
        '💪','🦾','🦿','🦵','🦶','👂','🦻','👃','🧠','🫀',
        '🫁','🦷','🦴','👀','👁️','👅','👄','🫦',
      ],
    },
    {
      name: 'Hearts',
      icon: '❤️',
      emojis: [
        '❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔',
        '❤️‍🔥','❤️‍🩹','❣️','💕','💞','💓','💗','💖','💘','💝',
        '💟','♥️','💌','💋','👄','💏','💑','👩‍❤️‍👨',
      ],
    },
    {
      name: 'Animals',
      icon: '🐶',
      emojis: [
        '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐻‍❄️','🐨',
        '🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐒',
        '🐔','🐧','🐦','🐤','🐣','🐥','🪿','🦆','🐦‍⬛','🦅',
        '🦉','🦇','🐺','🐗','🐴','🦄','🫎','🐝','🪲','🐛',
        '🦋','🐌','🐞','🐜','🪰','🪱','🐢','🐍','🦎','🦖',
        '🦕','🐙','🦑','🪼','🦐','🦞','🦀','🐡','🐠','🐟',
        '🐬','🐳','🐋','🦈','🪸','🐊','🐅','🐆','🦓','🫏',
        '🦍','🦧','🦣','🐘','🦛','🦏','🐪','🐫','🦒','🦘',
      ],
    },
    {
      name: 'Food',
      icon: '🍕',
      emojis: [
        '🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🫐',
        '🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑',
        '🫛','🥦','🥬','🥒','🌶️','🫑','🌽','🥕','🧄','🧅',
        '🫒','🥔','🍠','🫚','🥐','🥯','🍞','🫓','🥖','🥨',
        '🧀','🥚','🍳','🧈','🥞','🧇','🥓','🥩','🍗','🍖',
        '🌭','🍔','🍟','🍕','🫔','🌮','🌯','🫕','🥙','🧆',
        '🥗','🍝','🍜','🫘','🍲','🍛','🍣','🍱','🥟','🦪',
        '🍤','🍙','🍚','🍘','🍥','🥠','🥮','🍢','🍡','🍧',
        '🍨','🍦','🥧','🧁','🍰','🎂','🍮','🍭','🍬','🍫',
        '🍿','🍩','🍪','🌰','🥜','🫘','🍯',
      ],
    },
    {
      name: 'Activities',
      icon: '⚽',
      emojis: [
        '⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱',
        '🪀','🏓','🏸','🏒','🏑','🥍','🏏','🪃','🥅','⛳',
        '🪁','🛝','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼',
        '🛷','⛸️','🥌','🎿','⛷️','🏂','🪂','🏋️','🤼','🤸',
        '🏆','🥇','🥈','🥉','🏅','🎖️','🎗️','🎪','🤹','🎭',
        '🩰','🎨','🎬','🎤','🎧','🎼','🎹','🥁','🪘','🎷',
        '🎺','🪗','🎸','🪕','🎻','🪈','🎲','♟️','🎯','🎳',
      ],
    },
    {
      name: 'Objects',
      icon: '💡',
      emojis: [
        '⌚','📱','📲','💻','⌨️','🖥️','🖨️','🖱️','🖲️','💽',
        '💾','💿','📀','📼','📷','📸','📹','🎥','📞','☎️',
        '📟','📠','📺','📻','🎙️','🎚️','🎛️','🧭','⏱️','⏲️',
        '⏰','🕰️','💡','🔦','🕯️','🧯','🛢️','💸','💵','💴',
        '💶','💷','🪙','💰','💳','🪪','💎','⚖️','🪜','🧰',
        '🪛','🔧','🔨','⚒️','🛠️','⛏️','🪚','🔩','⚙️','🪤',
        '🧲','🔫','💣','🧨','🪓','🔪','🗡️','⚔️','🛡️','🚬',
      ],
    },
    {
      name: 'Flags',
      icon: '🏁',
      emojis: [
        '🏁','🚩','🎌','🏴','🏳️','🏳️‍🌈','🏳️‍⚧️','🏴‍☠️',
        '🇺🇸','🇬🇧','🇨🇦','🇦🇺','🇫🇷','🇩🇪','🇮🇹','🇪🇸',
        '🇯🇵','🇰🇷','🇨🇳','🇮🇳','🇧🇷','🇲🇽','🇷🇺','🇿🇦',
        '🇳🇬','🇪🇬','🇦🇷','🇨🇴','🇵🇪','🇨🇱','🇻🇪','🇪🇨',
      ],
    },
  ];

  filteredEmojis: string[] = [];

  constructor(private elRef: ElementRef) {}

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent) {
    if (this.visible && !this.elRef.nativeElement.contains(event.target)) {
      this.visible = false;
      this.visibleChange.emit(false);
    }
  }

  selectEmoji(emoji: string) {
    this.emojiSelect.emit(emoji);
  }

  setCategory(index: number) {
    this.activeCategory = index;
    this.searchTerm = '';
  }

  onSearch() {
    const term = this.searchTerm.trim().toLowerCase();
    if (!term) {
      this.filteredEmojis = [];
      return;
    }
    
    const matches: string[] = [];
    const allEmojis = this.categories.reduce((acc: string[], cat) => [...acc, ...cat.emojis], []);
    const uniqueEmojis = Array.from(new Set(allEmojis));
    
    for (const emoji of uniqueEmojis) {
      const keywords = EMOJI_NAMES[emoji] || '';
      if (keywords.includes(term) || emoji.includes(term)) {
        matches.push(emoji);
      }
    }
    
    this.filteredEmojis = matches;
  }

  get displayEmojis(): string[] {
    if (this.searchTerm.trim()) {
      return this.filteredEmojis;
    }
    return this.categories[this.activeCategory]?.emojis || [];
  }
}
